fn main() {
    println!("cargo:rerun-if-changed=src/lib.rs");

    let crate_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let out_dir = std::path::PathBuf::from(&crate_dir).join("include");
    std::fs::create_dir_all(&out_dir).ok();

    cbindgen::Builder::new()
        .with_crate(&crate_dir)
        .with_language(cbindgen::Language::C)
        .with_include_guard("WQL_H")
        .with_header("/* Generated by cbindgen — do not edit */")
        .generate()
        .expect("cbindgen failed")
        .write_to_file(out_dir.join("wql.h"));
}
