// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Person {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(int64, tag = "2")]
    pub age: i64,
    #[prost(message, optional, tag = "3")]
    pub address: ::core::option::Option<Address>,
    #[prost(enumeration = "Status", tag = "4")]
    pub status: i32,
    #[prost(bytes = "vec", tag = "5")]
    pub avatar: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, repeated, tag = "6")]
    pub tags: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Address {
    #[prost(string, tag = "1")]
    pub city: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub country: ::prost::alloc::string::String,
    #[prost(int32, tag = "3")]
    pub zip: i32,
    #[prost(message, optional, tag = "4")]
    pub location: ::core::option::Option<GeoPoint>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GeoPoint {
    #[prost(sint64, tag = "1")]
    pub lat: i64,
    #[prost(sint64, tag = "2")]
    pub lon: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Order {
    #[prost(int64, tag = "1")]
    pub id: i64,
    #[prost(string, tag = "2")]
    pub customer: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "3")]
    pub items: ::prost::alloc::vec::Vec<LineItem>,
    #[prost(int64, tag = "4")]
    pub total_cents: i64,
    #[prost(bool, tag = "5")]
    pub shipped: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LineItem {
    #[prost(string, tag = "1")]
    pub sku: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub quantity: i32,
    #[prost(int64, tag = "3")]
    pub price: i64,
    #[prost(message, repeated, tag = "4")]
    pub discounts: ::prost::alloc::vec::Vec<Discount>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Discount {
    #[prost(string, tag = "1")]
    pub code: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub percent: i32,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Status {
    Unknown = 0,
    Active = 1,
    Inactive = 2,
}
impl Status {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unknown => "UNKNOWN",
            Self::Active => "ACTIVE",
            Self::Inactive => "INACTIVE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "UNKNOWN" => Some(Self::Unknown),
            "ACTIVE" => Some(Self::Active),
            "INACTIVE" => Some(Self::Inactive),
            _ => None,
        }
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Team {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(int64, tag = "2")]
    pub id: i64,
    #[prost(message, repeated, tag = "3")]
    pub members: ::prost::alloc::vec::Vec<Member>,
    #[prost(string, tag = "4")]
    pub secret: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Member {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub role: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub secret: ::prost::alloc::string::String,
}
