/* Generated by cbindgen — do not edit */

#ifndef WQL_H
#define WQL_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Program contains predicate logic.
 */
#define WQL_PROGRAM_FILTER 1

/**
 * Program contains projection logic.
 */
#define WQL_PROGRAM_PROJECT 2

/**
 * Opaque handle to a loaded WQL program.
 */
typedef struct wql_program_t wql_program_t;

/**
 * Owned byte buffer returned by `wql_compile*`.
 * The caller must free with `wql_bytes_free`.
 */
typedef struct wql_bytes_t {
  uint8_t *data;
  uintptr_t len;
} wql_bytes_t;

/**
 * Program metadata returned by `wql_program_info`.
 *
 * Zero-initialize before calling `wql_program_info`. New fields will be
 * appended into `_reserved`; existing fields are stable.
 */
typedef struct wql_program_info_t {
  /**
   * Bitmask of `WQL_PROGRAM_FILTER` and/or `WQL_PROGRAM_PROJECT`.
   */
  uint8_t program_type;
  uint32_t instruction_count;
  uint8_t register_count;
  uint8_t max_frame_depth;
  uint8_t _reserved[24];
} wql_program_info_t;

/**
 * Result of `wql_eval`. Zero-initialize before calling.
 */
typedef struct wql_eval_result_t {
  /**
   * Bytes written to the output buffer (0 when the program has no projection).
   */
  uintptr_t output_len;
  /**
   * Whether the record passed the predicate (`true` when no predicate).
   */
  bool matched;
} wql_eval_result_t;

/**
 * Compile a WQL query to bytecode (schema-free mode).
 *
 * Returns a `wql_bytes_t` with the bytecode. On error, `data` is null and
 * `*errmsg` (if non-null) is set to a heap-allocated error string that
 * the caller must free with `wql_errmsg_free`.
 *
 * # Safety
 *
 * - `query` must be a valid UTF-8 C string (null-terminated).
 * - `errmsg`, if non-null, must point to a valid `*mut c_char` location.
 */
struct wql_bytes_t wql_compile(const char *query, char **errmsg);

/**
 * Compile a WQL query to bytecode with an optional schema.
 *
 * - `schema_ptr`/`schema_len`: serialized `FileDescriptorSet`. Pass null/0 for schema-free.
 * - `root_message`: fully-qualified message type (null for schema-free).
 *
 * # Safety
 *
 * - `query` must be a valid UTF-8 C string (null-terminated).
 * - `schema_ptr` (if non-null) must point to `schema_len` valid bytes.
 * - `root_message` (if non-null) must be a valid UTF-8 C string.
 * - `errmsg`, if non-null, must point to a valid `*mut c_char` location.
 */
struct wql_bytes_t wql_compile_with_schema(const char *query,
                                           const uint8_t *schema_ptr,
                                           uintptr_t schema_len,
                                           const char *root_message,
                                           char **errmsg);

/**
 * Load a compiled WQL program from bytecode.
 *
 * Returns a pointer to a `wql_program_t`, or null on error.
 *
 * # Safety
 *
 * - `bytecode` must point to `len` valid bytes.
 * - `errmsg`, if non-null, must point to a valid `*mut c_char` location.
 */
struct wql_program_t *wql_program_load(const uint8_t *bytecode, uintptr_t len, char **errmsg);

/**
 * Free a loaded WQL program.
 *
 * # Safety
 *
 * `program` must be a pointer returned by `wql_program_load`, or null.
 */
void wql_program_free(struct wql_program_t *program);

/**
 * Populate `out` with metadata about a loaded program.
 *
 * The caller should zero-initialize `out` before calling. This function
 * never fails.
 *
 * # Safety
 *
 * - `program` must be a valid pointer from `wql_program_load`.
 * - `out` must point to a valid `wql_program_info_t`.
 */
void wql_program_info(const struct wql_program_t *program, struct wql_program_info_t *out);

/**
 * Evaluate a WQL program against input bytes.
 *
 * Returns 0 on success, -1 on error. On success, `*result` is populated.
 * On error, `*errmsg` (if non-null) is set.
 *
 * For filter-only programs, pass `output = NULL` / `output_len = 0`.
 * For project-only programs, `result->matched` is always `true`.
 *
 * **Buffer sizing:** `output_len >= input_len` is always sufficient.
 *
 * # Safety
 *
 * - `program` must be a valid pointer from `wql_program_load`.
 * - `input` must point to `input_len` valid bytes.
 * - `output` (if non-null) must point to `output_len` writable bytes.
 * - `result` must point to a valid `wql_eval_result_t`.
 * - `errmsg`, if non-null, must point to a valid `*mut c_char` location.
 */
int32_t wql_eval(const struct wql_program_t *program,
                 const uint8_t *input,
                 uintptr_t input_len,
                 uint8_t *output,
                 uintptr_t output_len,
                 struct wql_eval_result_t *result,
                 char **errmsg);

/**
 * Run a filter (predicate-only) program on input bytes.
 *
 * Returns 1 if the record passes, 0 if filtered out, -1 on error.
 */
int32_t wql_filter(const struct wql_program_t *program,
                   const uint8_t *input,
                   uintptr_t input_len,
                   char **errmsg);

/**
 * Run a projection program. Writes projected output into the caller's buffer.
 *
 * Returns the number of bytes written to `output`, or -1 on error.
 */
int64_t wql_project(const struct wql_program_t *program,
                    const uint8_t *input,
                    uintptr_t input_len,
                    uint8_t *output,
                    uintptr_t output_len,
                    char **errmsg);

/**
 * Run a combined filter+projection program. Writes output into the caller's buffer.
 *
 * Returns `>= 0` bytes written (passed), `-1` filtered, `-2` error.
 */
int64_t wql_project_and_filter(const struct wql_program_t *program,
                               const uint8_t *input,
                               uintptr_t input_len,
                               uint8_t *output,
                               uintptr_t output_len,
                               char **errmsg);

/**
 * Free a `wql_bytes_t` returned by `wql_compile*`.
 *
 * # Safety
 *
 * `bytes.data` must be a pointer returned by `wql_compile*`, or null.
 */
void wql_bytes_free(struct wql_bytes_t bytes);

/**
 * Free an error message string returned via `errmsg` parameters.
 *
 * # Safety
 *
 * `msg` must be a pointer set by a `wql_*` function, or null.
 */
void wql_errmsg_free(char *msg);

#endif  /* WQL_H */
